### ISSUE TITLE
Include undirected graphs

### ISSUE THREAD

**Issue by oysteinsolheim** [CarloLucibello/GraphNeuralNetworks.jl#101]
Would it be a lot of work to include the possibility of having undirected graphs? Or is there any simple resolution of it?

**Comment by CarloLucibello** [comment]
While a `GNNGraph` is always undirected, it can model an undirected graph by having two directed edges for each undirected one. This is what is called a `bidirected` graph. 
```julia
julia> g = rand_graph(4, 6)
GNNGraph:
    num_nodes = 4
    num_edges = 6

julia> is_bidirected(g)
true

julia> edge_index(g)
([1, 1, 2, 2, 4, 4], [2, 4, 4, 1, 1, 2])

julia> g = rand_graph(4, 6, bidirected=false)
GNNGraph:
    num_nodes = 4
    num_edges = 6

julia> is_bidirected(g)
false

julia> edge_index(g)
([1, 1, 2, 3, 4, 4], [3, 4, 3, 2, 1, 3])
```
Undirected Graphs.jl graphs are automatically converted to bidirected GNNGraphs:
```julia
julia> gg = Graphs.erdos_renyi(10, 20)
{10, 20} undirected simple Int64 graph

julia> g = GNNGraph(gg)
GNNGraph:
    num_nodes = 10
    num_edges = 40

julia> is_directed(g)
true

julia> is_bidirected(g)
true
```
One utility function we can add is `add_reverse_edges(g)` to add the missing reverse edges to a graph and make it bidirected.

**Comment by oysteinsolheim** [comment]
Thanks, this is how I have resolved it. And that utility function would be useful. But the edge feature matrix would still have to be twice the size, right? Maybe it would be possible to just make a view of the directed version into that utility function as well (or another one).

**Comment by CarloLucibello** [comment]
> But the edge feature matrix would still have to be twice the size, right? 

right

>  Maybe it would be possible to just make a view of the directed version into that utility function as well (or another function).

we could consider that option

**Comment by learning-chip** [comment]
> just make a view of the directed version

The built-in `LinearAlgebra.Symmetric` might suffice.

Also notice a related discussion on DGL (https://github.com/dmlc/dgl/issues/2198#issuecomment-695985446) that

> Currently DGL maintains both CSR and CSC formats for storing a graph to allow efficient operations on in-neighbors as well as out-neighbors. For undirected graphs, CSR == CSC so one format is enough. We haven't implemented this optimization and we are considering it in the next release.
