### ISSUE TITLE
Question about temporal graph neural networks

### ISSUE THREAD

**Issue by DoktorMike** [CarloLucibello/GraphNeuralNetworks.jl#112]
I was wondering if there is a wish to also include temporal graph neural networks architectures in this repo or if that is preferred to be as a separate package?

There's PyTorch Geometric and PyTorch Geometric Temporal which are currently separate packages if I remember correctly but I wonder if it wouldn't be more natural to have these in the same repo in `GraphNeuralNetworks.jl`? 

Thoughts?

**Comment by CarloLucibello** [comment]
I would be totally fine with having temporal gnn. I'm not too worried about possible additional dependencies involved (DataFrames.jl maybe?). Seems a large undertaking though, we have to devise a few new graph types.

**Comment by DoktorMike** [comment]
I agree that there would not be many more dependencies (if any), but the architectures would be extended by temporal versions of course. 

This is what Pytorch Geometric Temporal currently provides I think. https://pytorch-geometric-temporal.readthedocs.io/en/latest/notes/resources.html

| Model                                                                | Temporal Layer | GNN Layer        | Proximity Order | Multi Type        |
| -----------------                                                    | -----------    | ---------------- | -----------     | ----------------- |
| [DCRNN](https://arxiv.org/abs/1707.01926)                            | GRU            | DiffConv         | Higher          | False             |
| [GConvGRU](https://arxiv.org/abs/1612.07659)                         | GRU            | Chebyshev        | Lower           | False             |
| [GConvLSTM](https://arxiv.org/abs/1612.07659)                        | LSTM           | Chebyshev        | Lower           | False             |
| [GC-LSTM](https://arxiv.org/abs/1812.04206)                          | LSTM           | Chebyshev        | Lower           | True              |
| [DyGrAE](https://ieeexplore.ieee.org/document/9073186)               | LSTM           | GGCN             | Higher          | False             |
| [LRGCN](https://arxiv.org/abs/1905.03994)                            | LSTM           | RGCN             | Lower           | False             |
| [EGCN-H](https://arxiv.org/abs/1902.10191)                           | GRU            | GCN              | Lower           | False             |
| [EGCN-O](https://arxiv.org/abs/1902.10191)                           | LSTM           | GCN              | Lower           | False             |
| [T-GCN](https://arxiv.org/abs/1811.05320)                            | GRU            | GCN              | Lower           | False             |
| [A3T-GCN](https://arxiv.org/abs/2006.11583)                          | GRU            | GCN              | Lower           | False             |
| [AGCRN](https://arxiv.org/abs/2007.02842)                            | GRU            | Chebyshev        | Higher          | False             |
| [MPNN LSTM](https://arxiv.org/abs/2009.08388)                        | LSTM           | GCN              | Lower           | False             |
| [STGCN](https://arxiv.org/abs/1709.04875)                            | Attention      | Chebyshev        | Higher          | False             |
| [ASTGCN](https://ojs.aaai.org/index.php/AAAI/article/view/3881)      | Attention      | Chebyshev        | Higher          | False             |
| [MSTGCN](https://ojs.aaai.org/index.php/AAAI/article/view/3881)      | Attention      | Chebyshev        | Higher          | False             |
| [GMAN](https://arxiv.org/pdf/1911.08415.pdf)                         | Attention      | Custom           | Lower           | False             |
| [MTGNN](https://arxiv.org/abs/2005.11650)                            | Attention      | Custom           | Higher          | False             |
| [AAGCN](https://arxiv.org/abs/1805.07694)                            | Attention      | Custom           | Higher          | False             |

**Comment by CarloLucibello** [comment]
we now have good support for temporal gnn convs thanks to @aurorarossi
