### ISSUE TITLE
Roadmap to merge GeometricFlux.jl and GraphNeuralNetworks.jl

### ISSUE THREAD

**Issue by yuehhua** [CarloLucibello/GraphNeuralNetworks.jl#132]
I think we should work together and avoid redundant work. It's no need to compete in the same comminuty.

Could you list the major difference of GraphNeuralNetworks.jl from GeometricFlux.jl?
I am curious about how can we redesign GeometricFlux.jl and keep the strength of GraphNeuralNetworks.jl.

I am thinking to migrate GraphSignals.jl to FluxML and you can put your design there.

**Comment by CarloLucibello** [comment]
GeometrixFlux.jl is deeply flawed, as I abundantly stated in multiple issues and rejected PRs over there. It needs a major redesign, but we already have a major redesign, it is GraphNeuralNetworks.jl. Why put again a lot of work into GeometricFlux to obtain the same result? How would this benefit the ecosystem? 

I think GeometricFlux should be discontinued and moved out of the FluxML org. The readme should be updated saying that development has moved on to GraphNeuralNetworks.jl. You are very welcome to contribute here: foundations are solid and there is lot of work to do in many different areas (see the open issues).

**Comment by yuehhua** [comment]
The major redesign should be the implementations, not the framework itself. I have outlined graph network and message-passing neural network in GeometricFlux.jl and the message function and update function should be able to overwrite to customize. I even don't see the update function in GraphNeuralNetworks.jl, not even graph network. Having graph network is to support more general neural netowrks, e.g. DeepSet, which doesn't use message-passing scheme. I am appreciate your soild foundations but it lack higher abstractions in GraphNeuralNetworks.jl.

I am currently busy with my PhD thesis and have little time to work on GeometrixFlux.jl. I think I will get it done in few weeks and get back to GeometrixFlux.jl.

**Comment by CarloLucibello** [comment]
A layer here can have multiple update and message functions, you can pass arbitrary closures to `propagate`. Any message passing can be achieved by using `apply_edges` and `propagate`. This is strictly more flexible than any abstraction defined in GeometricFlux and allows for efficient specializations based on the message function type. Maybe you should take some time to explore the domentation and the codebase.
