### ISSUE TITLE
hope can load dataset with GraphMLDatasets.jl

### ISSUE THREAD

**Issue by zsz00** [CarloLucibello/GraphNeuralNetworks.jl#149]
hope can load dataset with [GraphMLDatasets.jl](https://github.com/yuehhua/GraphMLDatasets.jl), it is contains more graph datasets.

**Comment by CarloLucibello** [comment]
[GraphMLDatasets.jl](https://github.com/yuehhua/GraphMLDatasets.jl) is agnostic to the GNN framework, so you can load a dataset from there and then construct a GNNGraph (or many) out of it. 
Is there a specific dataset you need? More generally I prefer to use MLDataset as a centralized dataset repository, If you want anything specific to be added you could open a issue there or create a PR

**Comment by zsz00** [comment]
yes, I  open a issue there  of OGB.
