### ISSUE TITLE
GSoC 2022

### ISSUE THREAD

**Issue by rutvij-25** [CarloLucibello/GraphNeuralNetworks.jl#157]
Hello @CarloLucibello, I would like to work on one of these projects this summer as a part of GSoC.
1) Adding Graph Convolutional layers
2) Adding models and examples
3) Adding graph datasets

I have been an active contributor to Metalhead.jl and model zoo, Here are my pull requests
1) [ESRGANs](https://github.com/FluxML/Metalhead.jl/pull/118) 
2) [Inception v4 and Inception Resnet v2](https://github.com/FluxML/Metalhead.jl/pull/129)
3) [Added weight initialization in DCGAN](https://github.com/FluxML/model-zoo/pull/311) (merged)
4) [I have coded Xception net but yet to start a pull request](https://github.com/FluxML/Metalhead.jl/issues/112)

I am familiar with the concepts of graphs and GNNs, I have trained a GNN in PyTorch on the ESOL dataset to predict if the molecule is soluble or not

**Comment by CarloLucibello** [comment]
I'll reply to this on slack

**Comment by CarloLucibello** [comment]
I'll reply to this on slack
