### ISSUE TITLE
message passing for multiple feature arrays 

### ISSUE THREAD

**Issue by MilkshakeForReal** [CarloLucibello/GraphNeuralNetworks.jl#166]
Hello and thank you for your excellent work!

If I have  multiple feature arrays, how should I define a customized `message` function? I want to have something like 

```julia
message(xi,xj,ui,uj) = xxx
```
This feature is available in `torch_geometric`. However, it seems like by design it is not possible in `GraphNeuralNetworks.jl` but we have to concatenate `x` and `u`?

**Comment by CarloLucibello** [comment]
You just put all your features inside a named tuple,  

```julia
ndata = (x = rand(3, num_nodes), b = rand(3, num_nodes))

message(xi, xj, e)= xi.x .+ xj.b

propagate(message, g, +,  x=ndata)
```

**Comment by MilkshakeForReal** [comment]
> You just put all your features inside a named tuple:
> 
> ```julia
> ndata = (x = rand(3, num_nodes), b = rand(3, num_nodes))
> 
> message(xi, xj, e)= xi.x .+ xj.b
> 
> propagate(message, g, +,  x=ndata)
> ```
> 
> Conversely, message functions can return named tuples as well.

Sorry, I'm still confused about how it works. The function `propagte` has keyword arguments `xi` and `xj`, but they are not assigned here. What is the keyword argument `x` here?

**Comment by CarloLucibello** [comment]
> Sorry, I'm still confused about how it works. What is the keyword argument x here? I couldn't find its definiton in the source code.

sorry, I thought we had that shortcut. I edited the comment. 

>By the way, I found a typo in the doc

thanks, fixed now!

**Comment by MilkshakeForReal** [comment]
I see. I honestly think it would be a good idea if we have 
```julia
propagate(message, g, +,  x=ndata)==propagate(message, g, +,  xi=ndata, xj=ndata)
```
since quite often we indeed have `x=xi=xj`
