### ISSUE TITLE
Add tutorials written in Pluto

### ISSUE THREAD

**Issue by CarloLucibello** [CarloLucibello/GraphNeuralNetworks.jl#168]
We can port these tutorials to GNN.jl:
- https://pytorch-geometric.readthedocs.io/en/latest/notes/colabs.html
- https://antoniolonga.github.io/Pytorch_geometric_tutorials/

To set up Pluto + Documenter, see this repo:
https://github.com/JuliaManifolds/Manopt.jl

**Comment by CarloLucibello** [comment]
See also #173 for more ideas

**Comment by Dsantra92** [comment]
Maybe add an option to download the pluto file also?

**Comment by Dsantra92** [comment]
Is Pluto the best thing for tutorials? 

Building the Static HTML file involves running the whole Pluto notebook (to get outputs and stuff). This rendering can often make life difficult for our CI. On the other hand, if we render the file in HTML locally and commit it,  we lose the whole purpose of using Pluto.jl.

**Comment by CarloLucibello** [comment]
closing this as completed
