### ISSUE TITLE
add radius_graph api

### ISSUE THREAD

**Issue by MilkshakeForReal** [CarloLucibello/GraphNeuralNetworks.jl#177]
Providing a `radius_graph` function would be useful when dealing with point clouds 

Ref:

https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/transforms/radius_graph.html

https://docs.dgl.ai/en/latest/_modules/dgl/transforms/functional.html#radius_graph

**Comment by CarloLucibello** [comment]
Similarly to [knn_graph](https://github.com/CarloLucibello/GraphNeuralNetworks.jl/blob/a65bb2ac998edb257523f01f3686ebac1de4519a/src/GNNGraphs/generate.jl#L122), this can be implemented using [NeighrestNeighbors.inrange](https://github.com/KristofferC/NearestNeighbors.jl#range-searches). You want to submit a PR?

**Comment by MilkshakeForReal** [comment]
> You want to submit a PR?

I can try it

**Comment by MilkshakeForReal** [comment]
Should we compute the neighbours for each subgraph or compute them for the batched graph and remove inter-graph edges afterwards? This is trickier than `knn_graph`

@CarloLucibello

**Comment by MilkshakeForReal** [comment]
I have finished it, let me add some tests!
