### ISSUE TITLE
Duplicate indexes in documents

### ISSUE THREAD

**Issue by MilkshakeForReal** [CarloLucibello/GraphNeuralNetworks.jl#187]
This is no big issue but I see duplicate indexes in the [doc](https://carlolucibello.github.io/GraphNeuralNetworks.jl/dev/api/gnngraph/#Graphs.LinAlg.adjacency_matrix)
![image](https://user-images.githubusercontent.com/38997672/174423852-3781d87e-5aee-4ad1-aea5-4bae1195dfb3.png)

**Comment by Dsantra92** [comment]
They are not exactly duplicate indexes. They are in fact different functions having the same names (function overloading).
