### ISSUE TITLE
Implement GraphWorld for fake graphs benchmarking

### ISSUE THREAD

**Issue by zsz00** [CarloLucibello/GraphNeuralNetworks.jl#188]
Ref. 
[GraphWorld: Fake Graphs Bring Real Insights for GNNs](https://arxiv.org/abs/2203.00112), 
[GraphWorld: Advances in Graph Benchmarking](http://ai.googleblog.com/2022/05/graphworld-advances-in-graph.html)
https://github.com/google-research/graphworld

A user of GraphWorld decides on a generative model for the task (in this case, node classification). GraphWorld comes with default generative models for node classification, link prediction, and graph property prediction

We propose GraphWorld as a complementary GNN benchmark that allows researchers to explore GNN performance on regions of graph space that are not covered by popular academic datasets. Furthermore, GraphWorld is cost-effective, running hundreds-of-thousands of GNN experiments on synthetic data with less computational cost than [one experiment on a large OGB dataset](https://ogb.stanford.edu/paper/kddcup2021/mag240m_DeeperBiggerBetter.pdf).

**Comment by CarloLucibello** [comment]
this dataset is pretty recent, we should see if it becomes reasonably popular. In any case, this issue should be moved to MLDatasets.jl

**Comment by zsz00** [comment]
ok, I moved to MLDatasets.jl
