### ISSUE TITLE
Support for multiple graphs in GNNGraph

### ISSUE THREAD

**Issue by Dsantra92** [CarloLucibello/GraphNeuralNetworks.jl#212]
GNNGraph support for multiple graphs is very limited. Also is GNNGraph the best name for a structure that is designed to hold multiple graphs?

One solution can be to coalesce all graph features into a single big graph just like PyG.

cc: @CarloLucibello

**Comment by CarloLucibello** [comment]
> One solution can be to coalesce all graph features into a single big graph just like PyG.

This is what already happens in GNNGraph. GNNGraph internally stores multiple graphs as a single graph along with a vector of node memberships.
