### ISSUE TITLE
Formatting errors in the tutorial

### ISSUE THREAD

**Issue by CarloLucibello** [CarloLucibello/GraphNeuralNetworks.jl#213]
The are some HTML artefacts in the tutorials, see https://carlolucibello.github.io/GraphNeuralNetworks.jl/dev/tutorials/introductory_tutorials/graph_classification_pluto/#Graph-Classification-with-Graph-Neural-Networks

**Comment by Dsantra92** [comment]
No such issues on my local. I am looking into this.

**Comment by Dsantra92** [comment]
Looks like an issue with the frontmatter and my local DemoCards.jl is ahead of the upstream. Working on some changes and will get them done by EOD.

**Comment by Dsantra92** [comment]
Should be fixed in the new DemoCards.jl release.

**Comment by CarloLucibello** [comment]
looks like #214 was not enough to fix it

**Comment by Dsantra92** [comment]
It's not a DemoCards issue, the md is not converted to html properly. Still not sure what's causing it.

**Comment by CarloLucibello** [comment]
@Dsantra92 did you menage to understand the cause of the error? We cannot overcome the issue I will have to revert to the old tutorials

**Comment by Dsantra92** [comment]
Thanks for the reminder, I will try to fix it within 2 days. If cannot find the issue by then, we can revert.

**Comment by CarloLucibello** [comment]
What do you mean? Fixed where?

**Comment by Dsantra92** [comment]
Got fixed here in https://github.com/rikhuijzer/PlutoStaticHTML.jl/pull/153.

**Comment by Dsantra92** [comment]
Should we make the PlutoStaticHTML version more explicit in the docs and make it more relaxed once it reaches v1?

**Comment by CarloLucibello** [comment]
Doing it in #218 , thanks

**Comment by CarloLucibello** [comment]
> Should we make the PlutoStaticHTML version more explicit in the docs and make it more relaxed once it reaches v1?

Actually that should be done in DemoCards.jl
