### ISSUE TITLE
Generation of documentation is very slow because of Pluto

### ISSUE THREAD

**Issue by natema** [CarloLucibello/GraphNeuralNetworks.jl#227]
Is Pluto the best thing for tutorials? 

_Originally posted by @Dsantra92 in https://github.com/CarloLucibello/GraphNeuralNetworks.jl/issues/168#issuecomment-1170477427_

It looks like the Pluto notebooks are responsible for making the local rendering of the documentation using `LiveServer` very long... 
Is there a clear desire to keep them or are you open to translating them into more classical tutorials, with the code directly displayed in documentation pages?

**Comment by CarloLucibello** [comment]
Yes that's annoying. Maybe the best thing would be to cache the generated markdown/html and recompile it only when needed. I think @Dsantra92 looked a bit into it but there were some problems. If the slowness cannot be solved I would be open to alternatives.

**Comment by CarloLucibello** [comment]
Closed in #230
