### ISSUE TITLE
GNN.jl in tutorials

### ISSUE THREAD

**Issue by aurorarossi** [CarloLucibello/GraphNeuralNetworks.jl#228]
In the gnn_intro and graph_classification tutorials, GNN.jl is often mentioned. I think it should be replaced with GraphNeuralNetworks.jl. Leaving GNN.jl may refer to another package someday.

**Comment by CarloLucibello** [comment]
I agree. I would gladly accept a PR, or I will get to it in a few days.

**Comment by CarloLucibello** [comment]
Closed in #229
