### ISSUE TITLE
Convolutions for GNNHeteroGraphs

### ISSUE THREAD

**Issue by CarloLucibello** [CarloLucibello/GraphNeuralNetworks.jl#254]
Now we have [`GNNHeteroGraph`](https://carlolucibello.github.io/GraphNeuralNetworks.jl/dev/gnnheterograph/)s but none of the convolutional layers support them. 

See https://pytorch-geometric.readthedocs.io/en/latest/notes/heterogeneous.html and in particular `to_hetero` for the interface PyG provides.

**Comment by Dsantra92** [comment]
I am willing to do this.

**Comment by arnauqb** [comment]
Has there been any progress on this? Am I correct on assuming that Message Passing is not yet supported for heterogeneous graphs? Thanks!

**Comment by Dsantra92** [comment]
Yes. Only the basic structure of HeteroGNNs is complete till date. Various graph functions and convolutions are not yet supported.

**Comment by CarloLucibello** [comment]
a preliminary implementation of a convolution for heterographs has been added in #300. Many rough edges though, feedbacks welcome,
