### ISSUE TITLE
GCNConv without normalization

### ISSUE THREAD

**Issue by FDemelas** [CarloLucibello/GraphNeuralNetworks.jl#277]
Hello, I'm trying to use GCNConv with negative edge weights, hence I would like to deactivate the normalization as clearly the square root of negative value is problematic.
Is it possible in some way to deactivate the normalization (but still use the edge weights) or change with a personalized normalization?

**Comment by CarloLucibello** [comment]
Hi, we don't support that currently. It would be nice to add the possibility of a custom normalization (PR welcome!). 
As a quick workaround you can define your own custom layer by copying and pasting the GCNConv implementation and 
removing the normalization
https://github.com/CarloLucibello/GraphNeuralNetworks.jl/blob/a7de26fc65e46f6f29208b8d365b9c0e79a1390a/src/layers/conv.jl#L125-L126

**Comment by FDemelas** [comment]
Thank you very much

**Comment by rbSparky** [comment]
Seems like a quick fix

@CarloLucibello should I create a PR that adds the possibility of custom normalization in GCNConv?
