### ISSUE TITLE
`add_edges` adds a non-existent edge to its `DataStore`

### ISSUE THREAD

**Issue by bicycle1885** [CarloLucibello/GraphNeuralNetworks.jl#280]
```
julia> using GraphNeuralNetworks

julia> g = GNNGraph([1], [2])
GNNGraph:
  num_nodes: 2
  num_edges: 1

julia> h = add_edges(g, Int[], Int[])  # adds no edges
GNNGraph:
  num_nodes: 2
  num_edges: 1

julia> g.edata._n  # this is one, of course
1

julia> h.edata._n  # but this is two, which is unexpected
2
```

I tested this on Julia 1.8.5 and the latest master branch of GraphNeuralNetworks.jl.

**Comment by bicycle1885** [comment]
Obviously this is cased by these lines, but I have no idea why we need them.
https://github.com/CarloLucibello/GraphNeuralNetworks.jl/blob/4e33163af67759ca45fbd461c383407260c56896/src/GNNGraphs/datastore.jl#L183-L184

**Comment by CarloLucibello** [comment]
I don't remember the reason for those cheks, I'll investigate
