### ISSUE TITLE
Graph classification: multiple graphs associated with a common label

### ISSUE THREAD

**Issue by msainsburydale** [CarloLucibello/GraphNeuralNetworks.jl#282]
Hello, many thanks for a great package. 

My task can be summarised as graph classification, where (i) multiple graphs are associated with a common label, and where (ii) all graphs have the same structure (i.e., only the node data changes between graphs). 

For example, a single input instance may be:

```
using GraphNeuralNetworks
d = 1                     # dimension of response variable
n = 100                   # number of nodes in the graph
e = 200                   # number of edges in the graph
m = 30                    # number of replicates of the graph
g = rand_graph(n, e)      # fixed structure for all graphs

# Multiple graphs: these would all be associated with a 
# single label that we would like to predict
graphs = [GNNGraph(g; ndata = rand(d, n)) for _ in 1:m]
```

The usual approach is to batch the graphs into a single super graph:  

```
using Flux: batch
batch(graphs)
# GNNGraph:
#   num_nodes: 3000
#   num_edges: 6000
#   num_graphs: 30
#   ndata:
# 	x = 1×3000 Matrix{Float64}
```

This approach is natural when the graph structure varies between graphs. However, it is inefficient when the graphs have a fixed structure (particularly with respect to memory, but presumably also in terms of performing the required operations during the propagation and readout modules). 

It would be more efficient to use a single graph with `ndata` storing the replicated data in, for example, the third dimension:

```
GNNGraph(g; ndata = rand(d, n, m))
```

This gives an error, since `ndata` should contain ~~matrices only, I think~~ arrays with the last dimension equal to the number of nodes. 

Do you have any suggestions for how best to proceed, in a way that aligns with the philosophy of the package?

**Comment by CarloLucibello** [comment]
This is an interesting application. `ndata` wants the last dimension to be the same as the number of nodes, but the support is not limited to matrices, so you can add node features as 
```julia
g.ndata.x = rand(d, m, n)
```
I'm not sure though that graph convolutions will handle properly these tensors. Ideally they should, so let me know how it goes.
