### ISSUE TITLE
Update `Flux.trainable`

### ISSUE THREAD

**Issue by aurorarossi** [CarloLucibello/GraphNeuralNetworks.jl#323]
I tried to use `GINCon` in a custom structure, but it gives me the same error as in [this issue](https://github.com/FluxML/Flux.jl/issues/2187), so I think we should update it so that the return type is a `NamedTuple`.
I can do a PR fixing this and in the other cases.

https://github.com/CarloLucibello/GraphNeuralNetworks.jl/blob/2e96319b6875a861278f6fc75b80aab64329e627/src/layers/conv.jl#L671

**Comment by CarloLucibello** [comment]
Yes, it should return a namedtuple
