### ISSUE TITLE
Outdated default package installation

### ISSUE THREAD

**Issue by Ochibobo** [CarloLucibello/GraphNeuralNetworks.jl#348]
The default installation seems to be **0.6.7**. This means features like _TGCN_ and _A3TGCN_ are missing. According to the registry the version ought to be **0.6.14**. Where could the issue be?

**Comment by CarloLucibello** [comment]
Probably you are installing GraphNeuralNetworks.jl in an environment where some other package is preventing you to have the latest version. 
Execute
```
 pkg> st --outdated
```
to understand where the problem is.

**Comment by Ochibobo** [comment]
You are actually right @CarloLucibello. Thanks.
