### ISSUE TITLE
A Logo is needed

### ISSUE THREAD

**Issue by CarloLucibello** [CarloLucibello/GraphNeuralNetworks.jl#35]

**Comment by 5tinzi** [comment]
A simple sketch of a logo representing the concept of graph and nodes fusion.  Just as a very personal suggestion.

![logo](https://user-images.githubusercontent.com/82663816/194987161-b94dc5a8-338a-4bde-bf1e-48ffef9896ed.png)

**Comment by CarloLucibello** [comment]
uuu, nice! Can you upload an `svg` version? Can we also brainstrom and visualize some variations? e.g. a smaller central node, no background circles, arrows along edges  representing messages ....

**Comment by 5tinzi** [comment]
I edited and re-uploaded a svg version https://github.com/CarloLucibello/GraphNeuralNetworks.jl/issues/35#issuecomment-1274032893. 

I have tried some slightly variations. But to better illustrate the message passing, maybe an animated gif would help?  
Just like the animated logo used in [DynamicalSystems.jl](https://juliadynamics.github.io/DynamicalSystems.jl/)
 
This is not a priority; wait a little longer and other people will have a better logo proposal.
 
![logoidea](https://user-images.githubusercontent.com/82663816/195053294-fe06f6b1-4d76-43c3-b77f-8b20db0183e2.png)

**Comment by CarloLucibello** [comment]
> I have tried some slightly variations.
so nice, thanks, let's think a few days about it

> But to better illustrate the message passing, maybe an animated gif would help?
we can also have animated gifs, but for the branding a static logo is needed as well

**Comment by CarloLucibello** [comment]
@5tinz the one I like the most is the 3rd in the first row, but I would like just arrows on the edges (no boxes). What do you think?

**Comment by 5tinzi** [comment]
sorry for responding so late, I missed the email notification.

I was worried it was too monotonous, so I also added some shadow. Here is how they looked like in the firefox brower. (in the case 4 and 5, I removed the arrows cause too much of them looked messy)
![logo](https://user-images.githubusercontent.com/82663816/210161195-ea077249-3165-4671-b566-31d63357b3ec.png)

The SVG format file is in the attachment. If there are other ideas, I can keep modifying them.

[logo_in_svg.tar.gz](https://github.com/CarloLucibello/GraphNeuralNetworks.jl/files/10328301/logo_in_svg.tar.gz)

**Comment by CarloLucibello** [comment]
Thanks @5tinzi for carrying this though. 
Can I bother you with a few more variations?
The ones that I like most are 1 and 4. 
I would explore the following variation on 4:
- all lines same width. Maybe on the thin side?
- no "aurea"
- w/ and w/o arrows. We could try with a lighter arrowhead, just v-shaped without filling

**Comment by 5tinzi** [comment]
Indeed, the thin edge looks better, I personally favor v9 or v10 here:
1. the solid line represents the message passing, 
2. the dashed line corresponds to the  link prediction task
3. the color means node classification 
The graph classification is hard to show explicitly here, 
however, it is easy to comprehend that the whole graph could be the input of further classification
![logos](https://user-images.githubusercontent.com/82663816/210207215-017a9474-f447-48e9-bce4-b6738a05b978.png)
 
finally, I am worried that the sketch was too simple, it only contains "graph" and "message passing" and does not reflect the combination of neural network, but I don't have an idea yet.


Hope this could provide some help.
[logo_in_svg_2.tar.gz](https://github.com/CarloLucibello/GraphNeuralNetworks.jl/files/10330536/logo_in_svg_2.tar.gz)

**Comment by CarloLucibello** [comment]
Looks like we converged, I will go with v9.
Now I need to figure out how to use it :)
Can I credit you in the Readme or somewhere else?

**Comment by 5tinzi** [comment]
It is not required. Please feel free to use, modify or replace it. No copyright is reserved.
GraphNeuralNetworks.jl has helped me a lot in my current PhD project, thank you.

**Comment by CarloLucibello** [comment]
added the logo in the README, thanks again @5tinzi

**Comment by 5tinzi** [comment]
The current logos all have white background,
here are them without background color.
Just in case of need.

[logo_no_background.tar.gz](https://github.com/CarloLucibello/GraphNeuralNetworks.jl/files/10357037/logo_no_background.tar.gz)
