### ISSUE TITLE
documentation proposal

### ISSUE THREAD

**Issue by LegionAtol** [CarloLucibello/GraphNeuralNetworks.jl#357]
Hi @CarloLucibello ,
I'm new to GraphNeuralNetowrk.jl and I'd like to bring my contribution to the world of GNNs and julia:)
For a few days I've been working on a quick-start guide which presents the theoretical basis of GNNs with code snippets using GraphNeuralNetowrk.jl
If you consider it useful, I would like to continue with the creation, I leave the link of the draft (to be refined and continued obviously) to give you an idea of how it could turn out: https://github.com/LegionAtol/LegionAtol/blob/6066dd60064331d5c174685d547e065cd14743dd/GNN.pdf

Thanks

**Comment by CarloLucibello** [comment]
Hi,
we surely need more well-written documentation, tutorials, and examples. If you plan to create a self-consistent document and host it somewhere, I would be very happy to add a link to it from this repo's docs.

If you want to integrate more organically into the [existing documentation](https://carlolucibello.github.io/GraphNeuralNetworks.jl/dev/) instead,
we can think about the best way to move forward. Ideally, the documentation should 
be organized according to the [documentation system](https://documentation.divio.com/), although we currently do not strictly adhere to this standard.

**Comment by CarloLucibello** [comment]
closing since things didn't move on. Feel free to reopen if needed.
