### ISSUE TITLE
support Lux

### ISSUE THREAD

**Issue by CarloLucibello** [CarloLucibello/GraphNeuralNetworks.jl#372]
This package is built on top of Flux.jl, but we could consider also supporting Lux.jl since it is being used in some part of the ecosystem. It is not clear if supporting both can be done without a lot of code duplication.

cc @avik-pal

**Comment by avik-pal** [comment]
The easiest way to do that would be to provide NNlib like primitives instead of defining `(l::GCNConv)(....)`, etc.

**Comment by CarloLucibello** [comment]
I'm going to factor out a DL-framework agnostic GNNlib.jl package.

**Comment by CarloLucibello** [comment]
closing in favor of more specific #461
