### ISSUE TITLE
add support to edge weight in GCNConv

### ISSUE THREAD

**Issue by CarloLucibello** [CarloLucibello/GraphNeuralNetworks.jl#40]
and possibly other layers as well

**Comment by tclements** [comment]
Thanks for the package - would love to see this implemented!

**Comment by CarloLucibello** [comment]
@tclements done! Let me know if you find the interface convenient or if there is anything that can be improved

**Comment by tclements** [comment]
Awesome, work - I'll give it a try, thanks!
