### ISSUE TITLE
Error in one of the examples in the Working with GNNGraph page

### ISSUE THREAD

**Issue by achiverram28** [CarloLucibello/GraphNeuralNetworks.jl#401]
<img width="869" alt="B2FF88BC-0ADD-4FEB-AA50-CDE2F498BA13" src="https://github.com/CarloLucibello/GraphNeuralNetworks.jl/assets/97288756/05dfe30d-8a70-4daa-8f9c-46ef0782702d">

The number of edges in gall wont be 9600 as its a rand_graph initiation with 30 edges , it will be `160 x 30 = 4800`, it wont be `4800 x 2`

<img width="531" alt="1B81CC51-D4CC-4032-ADD7-FACAB260752A" src="https://github.com/CarloLucibello/GraphNeuralNetworks.jl/assets/97288756/40b0ee4c-53ac-496f-8975-25c327d42c36">

When I make `data = [rand_graph(10, 60, ndata=rand(Float32, 3, 10)) for _ in 1:160]` , then the number of edges will be `160 x 60 = 9600`

<img width="389" alt="B4735B74-6D5F-4296-A450-48101A091D2B" src="https://github.com/CarloLucibello/GraphNeuralNetworks.jl/assets/97288756/c7034c3a-adf6-483b-8bd7-73bb35a750b7">

**Comment by achiverram28** [comment]
Can I make the changes in the doc of it

**Comment by CarloLucibello** [comment]
yes please, the assert should be changed

**Comment by CarloLucibello** [comment]
closed in #403
