### ISSUE TITLE
Duplicated method definitions of GINConv

### ISSUE THREAD

**Issue by bicycle1885** [CarloLucibello/GraphNeuralNetworks.jl#406]
I see the following warning while precompiling the package:
```
WARNING: Method definition (::GraphNeuralNetworks.GINConv{R<:Real, NN, A})(GraphNeuralNetworks.GNNGraphs.TemporalSnapshotsGNNGraph, AbstractArray{T, 1} where T) in module GraphNeu
ralNetworks at /home/kenta/.julia/packages/GraphNeuralNetworks/a5Jzz/src/layers/temporalconv.jl:190 overwritten at /home/kenta/.julia/packages/GraphNeuralNetworks/a5Jzz/src/layers
/temporalconv.jl:210.
```

As the message says, we can find duplicated method definitions for `GINConv`:
https://github.com/CarloLucibello/GraphNeuralNetworks.jl/blob/76711ba361e9065371e256ab5513099a163c5ef3/src/layers/temporalconv.jl#L190
https://github.com/CarloLucibello/GraphNeuralNetworks.jl/blob/76711ba361e9065371e256ab5513099a163c5ef3/src/layers/temporalconv.jl#L210

**Comment by aurorarossi** [comment]
Line 190 was added in 0780fe8e43a5394b692a074d4a211f01acf612a9 then duplicated in 50ebac39aeafdb2be2579dd9aeb097c503a29433
I will fix this, thanks for pointing this out !
