### ISSUE TITLE
turn this into a monorepo

### ISSUE THREAD

**Issue by CarloLucibello** [CarloLucibello/GraphNeuralNetworks.jl#433]
We want to host in this repo 2 packages, GNNlib.jl (#432) and GraphNeuralNetworks.jl. In the future there will be another frontend like GraphNeuralNetworks.jl based on Lux.jl.

We want to host all of that into a single repo instead of multiple ones in order to facilitate development, since very likely a PR will often change both GNNlib.jl and the other repo.

Useful discussions on monorepos:
https://discourse.julialang.org/t/anything-to-be-wary-of-when-registering-a-subpackage/112459
https://discourse.julialang.org/t/how-beacon-packages-julia-code-in-a-monorepo/90822/9
https://github.com/JuliaLang/Pkg.jl/pull/3263

Examples of monorepo:
https://github.com/tecosaur/DataToolkit.jl
https://github.com/MakieOrg/Makie.jl
https://github.com/ITensor/ITensors.jl
https://github.com/JuliaGeo/GeoInterface.jl
https://github.com/gdalle/DifferentiationInterface.jl
https://github.com/timholy/SnoopCompile.jl

**Comment by gdalle** [comment]
To be fair, I only added the Register action because a user asked for it repeatedly in an issue, but I don't actually use it :innocent:

**Comment by gdalle** [comment]
I also havent completely figured out the testing mechanism cause both repos depend on one another for tests. At the moment I think you cannot test `DifferentiationInterface` if you downloaded it alone, which kinda sucks

**Comment by CarloLucibello** [comment]
> To be fair, I only added the Register action because a user asked for it repeatedly in an issue, but I don't actually use it 😇

I did try but cannot manage to make it work https://github.com/CarloLucibello/GraphNeuralNetworks.jl/actions

**Comment by gdalle** [comment]
Yeah I had tried that a few times too and hit similar errors that I didn't understand, so I gave up

**Comment by CarloLucibello** [comment]
For local development instead I found this comment pointing at a solution
https://github.com/JuliaLang/Pkg.jl/pull/3263#issuecomment-1875788646
So I think that instead of `dev`ing the packages, one has to clone the repo and try to use this shared manifest trick.
I don't know if julia 1.10 supports it already, probably not.

**Comment by gdalle** [comment]
Right but my point about local testing is that people should be able to do
```julia
using Pkg
Pkg.add("DifferentiationInterface")
Pkg.test("DifferentiationInterface")
```
and it should just work. Right now it doesn't because my DifferentiationInterface `runtests.jl` looks for DifferentiationInterfaceTest in the folder next door

**Comment by gdalle** [comment]
>  I don't know if julia 1.10 supports it already, probably not.

Doesn't show up on https://pkgdocs.julialang.org/v1.10/toml-files/

**Comment by gdalle** [comment]
I have figured out a better workflow for mutually dependent tests:

https://github.com/gdalle/DifferentiationInterface.jl/blob/571133f676a2f2ebe70d35f9d779a5aa274dd3ef/DifferentiationInterface/test/runtests.jl#L7-L10

https://github.com/gdalle/DifferentiationInterface.jl/blob/571133f676a2f2ebe70d35f9d779a5aa274dd3ef/DifferentiationInterfaceTest/test/runtests.jl#L8-L11

**Comment by CarloLucibello** [comment]
closing as complited

**Comment by gdalle** [comment]
How did you solve the problem of the sibling packages needing to get the local versions of their friends during tests? Manual Pkg ops?

**Comment by CarloLucibello** [comment]
yes. you can see that in the CI workflows
