### ISSUE TITLE
Maybe state difference with GeometricFlux.jl.

### ISSUE THREAD

**Issue by alex-s-gardner** [CarloLucibello/GraphNeuralNetworks.jl#435]
Snooping around for a julia GNN package and it would be helpful to know how  GraphNeuralNetworks.jl differs from GeometricFlux.jl... maybe it's just in scope and ease of use?

**Comment by CarloLucibello** [comment]
GNN.jl is actively mantained and I think it has a cleaner interface. More differences are elencated in #81
