### ISSUE TITLE
Implementation of recommender system based on GNN

### ISSUE THREAD

**Issue by marthinkondjeni** [CarloLucibello/GraphNeuralNetworks.jl#473]
I'm currently working on a project that involves implementing a recommender system based on GNN. I would greatly appreciate any guidance or pointers related to implementing a recommender system using GNN.

**Comment by CarloLucibello** [comment]
I suggest you find a reference paper or blog article and try to reimplement it. I guess some ingredients could be a link prediction task and heterogenous graphs (e.g. bipartite graphs with `user` nodes and `item` nodes). If you find a good reference I will be happy to help with the implementation.

**Comment by marthinkondjeni** [comment]
I found this paper [https://arxiv.org/pdf/1910.05552]. Below is the implementation in python [https://github.com/CRIPAC-DIG/Fi_GNN]
