### ISSUE TITLE
Comparison to GeometricFlux.jl

### ISSUE THREAD

**Issue by adrhill** [CarloLucibello/GraphNeuralNetworks.jl#502]
Hi Carlo!
I'm looking for a GNN package and found both GraphNeuralNetworks.jl and GeometricFlux.jl.
The README mentions that this package is inspired by the latter, but doesn't go into detail.

A summary of the differences between the two packages in the README would be helpful when trying to decide which one to use.

**Comment by CarloLucibello** [comment]
Hi Adrian,
yes this comes up often 
https://github.com/CarloLucibello/GraphNeuralNetworks.jl/issues/2
https://github.com/CarloLucibello/GraphNeuralNetworks.jl/issues/81

I think GeometricFlux is also not actively maintained, but I may be wrong.
