### ISSUE TITLE
Adding a GATv2 layer

### ISSUE THREAD

**Issue by DoktorMike** [CarloLucibello/GraphNeuralNetworks.jl#74]
Awesome package you wrote. I just read up on GATv2 which has a lot of claims of being superior to GAT so just thought it might be cool to add that too.

- The repo is here: https://github.com/tech-srl/how_attentive_are_gats
- Paper: https://arxiv.org/abs/2105.14491

It's also featured in PytorchGeometric and DGL.

**Comment by CarloLucibello** [comment]
Thanks! Yes, that would be a nice addition. Easy to implement by tweaking a bit the gat layer we already have. Feel free to file a PR if you want, otherwise I can add it next week

**Comment by DoktorMike** [comment]
> Thanks! Yes, that would be a nice addition. Easy to implement by tweaking a bit the gat layer we already have. Feel free to file a PR if you want, otherwise I can add it next week

I'll give it a go. :)

**Comment by CarloLucibello** [comment]
Appendix F of the paper contains some useful details

**Comment by CarloLucibello** [comment]
Closed in #97
