### ISSUE TITLE
Explainer vs GeometricFlux

### ISSUE THREAD

**Issue by bhalonen** [CarloLucibello/GraphNeuralNetworks.jl#81]
Hello,

I'm an experience Julia developer, and I am getting into GNN's. I am looking at your package and GeometricFlux, and I almost defaulted to GeometricFlux on popularity, but it appears you have many nice features that I might prefer. 

Can you provide a "simple explanation" of why this package vs GeometricFlux (and vice versa)?

Great work by the way!

**Comment by AriMKatz** [comment]
https://github.com/CarloLucibello/GraphNeuralNetworks.jl/issues/2

**Comment by CarloLucibello** [comment]
Well, if you have to perform graph-level tasks (e.g. graph classification), the choice is brainless, 
GF.jl doesn't support batched graphs.

The performance comparison in #82 is another compelling argument inf favor of GNN.jl: on CPU, the Cora example runs 4x faster. On GPU, I couldn't manage to get it working for GF.jl, while GNN.jl gains another 10x. 

Honestly, at the moment I cannot think of a single reason to recommend GF.jl over GNN.jl (performance, features, flexibility, simplicity, documentation, ...)

> Great work by the way!

thanks!

**Comment by bhalonen** [comment]
Yeah, more or less that's what I concluded... this is just much much higher quality and I'm just a beginner in GNNs.

I'm working on integrating this to AlphaZero.jl, so I may have bunch of questions, hope you have patience.

**Comment by bhalonen** [comment]
Batched operations very important, obviously. Basically a requirement.

**Comment by CarloLucibello** [comment]
> I'm working on integrating this to AlphaZero.jl, so I may have bunch of questions, hope you have patience.

Cool, I'm very happy to provide any kind support
