### ISSUE TITLE
Hash function for GNNGraph

### ISSUE THREAD

**Issue by bhalonen** [CarloLucibello/GraphNeuralNetworks.jl#87]
Would it make sense to have a hash function for GNNGraph?

**Comment by CarloLucibello** [comment]
What do you mean? You want to hash a graph?

**Comment by bhalonen** [comment]
For context I'm working on integrating your package into AlphaZero, where the state of the "game" is a key in a dictionary. We just naively used the GNNGraph in this key as a part of a named tuple as a description of our state.

It wouldn't be a big deal to just flatten the state to component vectors and reassemble into a GNNGraph, but just simpler to not.

**Comment by bhalonen** [comment]
https://github.com/sbromberger/LightGraphs.jl/issues/1256

There was a discussion of this, and decided against adding for Graphs now that i do some research.
